Create ru.po
FineFindus/eyedropper pull request #36
Opened 2023-01-25 23:20 UTC by vorons

2023-01-26 21:36 UTC, FineFindus requested changes
Thanks for the translation!
I found two minor issues which should addressed before merging, and please also add the language code to `po/LINGUAS`.

Will you continue to maintain this translation?

2023-01-26 21:36 UTC, FineFindus commented on po/ru.po
> +msgstr ""
Please translate them as well, they are used in the overview search and are language specific.

2023-01-26 21:36 UTC, FineFindus commented on po/ru.po
> +msgstr ""
I think you might have forgotten to translate these?

2023-01-26 22:33 UTC, vorons commented
Several corrections added.

I can support the translation as far as possible.

2023-01-27 07:12 UTC, FineFindus commented
Thanks!

2023-01-27 07:13 UTC, merged