Add glvec color format
FineFindus/eyedropper pull request #59
Opened 2023-03-22 20:34 UTC by yuraiz

rgb / rgba format with float values between 0.0-1.0 

can be used for shaders as vec3 / vec4
also can be configured as gdk::RGBA::new({r}, {g}, {b}, {a})

![image](https://user-images.githubusercontent.com/63008755/227030221-1522f4bc-d994-4a19-9abd-c4ac825cc70b.png)

2023-03-23 16:23 UTC, FineFindus requested changes
Thanks for the contribution, but I think this could be rewritten to a more generic solution to the issue. As it is only a different representation of the `rgb` format, it would be better to add a preference for changing the [numeric representation of RGB](https://en.wikipedia.org/wiki/RGB_color_model?useskin=vector#Numeric_representations), similar to how the `AlphaPosition` works. 
The user could then set `vec3` as a custom format for RGB.

2023-03-23 16:23 UTC, FineFindus commented on src/colors/formatter.rs
> +                self.color.blue as f32 / 255.0
This should support changing the precision/length via `self.precision`

2023-03-24 07:02 UTC, yuraiz commented
I don't think that it would be useful to have a separate parameter for rgb representation
With separate formats I can use values for both css and glsl

Also internal representation is still 8-bit per channel so other notations than Arithmetic, Percentage and Digital 8-bit per channel are meaningless

2023-03-24 08:37 UTC, yuraiz commented
BTW isn't it's more precise to use f64 as representation, as I see ashpd color request returns [color with f64 representation](https://bilelmoussaoui.github.io/ashpd/ashpd/desktop/screenshot/struct.Color.html)

2023-03-24 20:12 UTC, FineFindus commented
>  With separate formats I can use values for both css and glsl

That's a valid point, maybe this could be solved be opening multiple windows (currently not possible)? The issue I'm seeing is that, a less technical / somewhat technical user, who just hasn't worked with shaders yet, might be confused what  `vec3` is, as it does not appear in with other common color formats. And since it is only renamed RGB, it would make sense, to only have one RGB format, instead of multiple, which just differ in how the values are depicted.

> Also internal representation is still 8-bit per channel so other notations than Arithmetic, Percentage and Digital 8-bit per channel are meaningless

Should be a pretty easy change, to switch from 8-bit to 32-bit. In any case, I think just switching between those three notations would still be valuable.

> BTW isn't it's more precise to use f64 as representation, as I see ashpd color request returns [color with f64 representation](https://bilelmoussaoui.github.io/ashpd/ashpd/desktop/screenshot/struct.Color.html)

That's correct, but `gtk::gdk::RGBA` uses f32, which was used before I implemented color picking and just forgot to update it everywhere else.

2023-03-25 16:59 UTC, FineFindus commented
XYZ and HWB are both well known color models, whereas vec3 technically isn't even one, as it just uses RGB values.

2023-04-08 11:17 UTC, FineFindus requested changes
Sorry for the long silence. Personally, I see your problem with changing the settings, it is not a good long term solution. It would open up discussions about adding other settings to the menu, cluttering it up unnecessarily for others who may not use the RGB format.

2023-10-03 12:33 UTC, closed without merging